# Generated by Django 4.2.5 on 2023-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='importado',
        ),
    ]
