# Generated by Django 4.2.6 on 2023-10-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='funcionario',
        ),
    ]
