# Generated by Django 4.2.6 on 2023-10-12 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0009_alter_produto_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='funcionario',
            field=models.ForeignKey(default='empresas.User', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
