# Generated by Django 4.2.6 on 2023-10-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_produto_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='funcionario',
            new_name='usuario',
        ),
    ]
