# Generated by Django 4.2.6 on 2023-10-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_rename_funcionario_produto_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='usuario',
            new_name='funcionario',
        ),
    ]
