# Generated by Django 4.2.6 on 2023-10-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_profile_bio_alter_profile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
